version: '3.7'

services:
  api:
    build: .
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"  

  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "xbox_store"
    volumes:
      - ./db/migrations/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server --requirepass secret


